// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: configuration.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct FetchConfigurationResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var enableTraceNetworkLatency: Bool = false

  public var enableErrorReport: Bool = false

  public var appleMusicDeveloperToken: String = String()

  public var timAppID: String = String()

  public var timSign: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct FetchConfigurationRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension FetchConfigurationResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "FetchConfigurationResponse"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "enable_trace_network_latency"),
    2: .standard(proto: "enable_error_report"),
    3: .standard(proto: "apple_music_developer_token"),
    4: .standard(proto: "tim_app_id"),
    5: .standard(proto: "tim_sign"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.enableTraceNetworkLatency) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.enableErrorReport) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.appleMusicDeveloperToken) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.timAppID) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.timSign) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.enableTraceNetworkLatency != false {
      try visitor.visitSingularBoolField(value: self.enableTraceNetworkLatency, fieldNumber: 1)
    }
    if self.enableErrorReport != false {
      try visitor.visitSingularBoolField(value: self.enableErrorReport, fieldNumber: 2)
    }
    if !self.appleMusicDeveloperToken.isEmpty {
      try visitor.visitSingularStringField(value: self.appleMusicDeveloperToken, fieldNumber: 3)
    }
    if !self.timAppID.isEmpty {
      try visitor.visitSingularStringField(value: self.timAppID, fieldNumber: 4)
    }
    if !self.timSign.isEmpty {
      try visitor.visitSingularStringField(value: self.timSign, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: FetchConfigurationResponse, rhs: FetchConfigurationResponse) -> Bool {
    if lhs.enableTraceNetworkLatency != rhs.enableTraceNetworkLatency {return false}
    if lhs.enableErrorReport != rhs.enableErrorReport {return false}
    if lhs.appleMusicDeveloperToken != rhs.appleMusicDeveloperToken {return false}
    if lhs.timAppID != rhs.timAppID {return false}
    if lhs.timSign != rhs.timSign {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FetchConfigurationRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "FetchConfigurationRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let _ = try decoder.nextFieldNumber() {
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: FetchConfigurationRequest, rhs: FetchConfigurationRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
