//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: im.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate `IMConfigServiceClient`, then call methods of this protocol to make API calls.
internal protocol IMConfigServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: IMConfigServiceClientInterceptorFactoryProtocol? { get }

  func fetchIMConfig(
    _ request: FetchIMConfigRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<FetchIMConfigRequest, FetchIMConfigResponse>
}

extension IMConfigServiceClientProtocol {
  internal var serviceName: String {
    return "IMConfigService"
  }

  /// Unary call to FetchIMConfig
  ///
  /// - Parameters:
  ///   - request: Request to send to FetchIMConfig.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func fetchIMConfig(
    _ request: FetchIMConfigRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<FetchIMConfigRequest, FetchIMConfigResponse> {
    return self.makeUnaryCall(
      path: "/IMConfigService/FetchIMConfig",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeFetchIMConfigInterceptors() ?? []
    )
  }
}

internal protocol IMConfigServiceClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'fetchIMConfig'.
  func makeFetchIMConfigInterceptors() -> [ClientInterceptor<FetchIMConfigRequest, FetchIMConfigResponse>]
}

internal final class IMConfigServiceClient: IMConfigServiceClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: IMConfigServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the IMConfigService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: IMConfigServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

