//AccountServiceClient

import Security


typealias RiviaAccountServiceClient = AccountServiceClient
typealias RiviaAccountLoginWithOAuthRequest = LoginWithOAuthRequest
typealias RiviaAccountLoginWithOAuthResponse = LoginResponse

typealias RiviaEventServiceClient = EventServiceClient
typealias RiviaPublishUserEventRequest = PublishUserEventRequest
typealias RiviaPublishUserEventResponse = PublishUserEventResponse


typealias RiviaUserServiceClient = UserServiceClient
typealias RiviaFetchUserRequest = FetchUserRequest
typealias RiviaFetchUserResponse = FetchUserResponse

typealias RiviaFriendshipServiceClient = FriendshipServiceClient
typealias RiviaFriendshipFetchFriendsRequest = FetchFriendsRequest
typealias RiviaFriendshipFetchFriendsResponse = FetchFriendsResponse
typealias RiviaFriendshipFetchFollwersRequest = FetchFollowersRequest
typealias RiviaFriendshipFetchFollwersResponse = FetchFollowersResponse


typealias RiviaIMConfigServiceClient = IMConfigServiceClient
typealias RiviaIMFetchConfigRequest = FetchIMConfigRequest
