//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: user.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate `UserServiceClient`, then call methods of this protocol to make API calls.
public protocol UserServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: UserServiceClientInterceptorFactoryProtocol? { get }

  func fetchUser(
    _ request: FetchUserRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<FetchUserRequest, FetchUserResponse>
}

extension UserServiceClientProtocol {
  public var serviceName: String {
    return "UserService"
  }

  /// Unary call to FetchUser
  ///
  /// - Parameters:
  ///   - request: Request to send to FetchUser.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func fetchUser(
    _ request: FetchUserRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<FetchUserRequest, FetchUserResponse> {
    return self.makeUnaryCall(
      path: "/UserService/FetchUser",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeFetchUserInterceptors() ?? []
    )
  }
}

public protocol UserServiceClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'fetchUser'.
  func makeFetchUserInterceptors() -> [ClientInterceptor<FetchUserRequest, FetchUserResponse>]
}

public final class UserServiceClient: UserServiceClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: UserServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the UserService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: UserServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

